export const HISTOIRE_SAVE_REQUEST =   'HISTOIRE_SAVE_REQUEST';
export const HISTOIRE_SAVE_SUCCESS =   'HISTOIRE_SAVE_SUCCESS';
export const HISTOIRE_SAVE_FAIL =      'HISTOIRE_SAVE_FAIL';

export const HISTOIRE_LIST_REQUEST =   'HISTOIRE_LIST_REQUEST';
export const HISTOIRE_LIST_SUCCESS =   'HISTOIRE_LIST_SUCCESS';
export const HISTOIRE_LIST_FAIL =      'HISTOIRE_LIST_FAIL';

export const HISTOIRE_UPDATE_REQUEST = 'HISTOIRE_UPDATE_REQUEST';
export const HISTOIRE_UPDATE_SUCCESS = 'HISTOIRE_UPDATE_SUCCESS';
export const HISTOIRE_UPDATE_FAIL =    'HISTOIRE_UPDATE_FAIL';