export const PAGE_SAVE_REQUEST = 'PAGE_SAVE_REQUEST';
export const PAGE_SAVE_SUCCESS = 'PAGE_SAVE_SUCCESS';
export const PAGE_SAVE_FAIL =    'PAGE_SAVE_FAIL';

export const PAGE_LIST_REQUEST = 'PAGE_LIST_REQUEST';
export const PAGE_LIST_SUCCESS = 'PAGE_LIST_SUCCESS';
export const PAGE_LIST_FAIL =    'PAGE_LIST_FAIL';

export const PAGE_UPDATE_REQUEST = 'PAGE_UPDATE_REQUEST';
export const PAGE_UPDATE_SUCCESS = 'PAGE_UPDATE_SUCCESS';
export const PAGE_UPDATE_FAIL =    'PAGE_UPDATE_FAIL';